# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160412_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensegroup',
            old_name='description',
            new_name='name',
        ),
    ]
